export type Category = (typeof ALL_GAMES)[number]["category"];

export const ALL_GAMES = [
  {
    title: "Med andra ord",
    emoji: "🎯",
    slug: "med-andra-ord",
    color: "bg-gray-50",
    category: "sallskapsspel",
    url: "/sallskapsspel/med-andra-ord",
  },
  {
    title: "200 Frågor",
    emoji: "❓",
    slug: "200-fragor",
    color: "bg-blue-50",
    category: "quiz",
    url: "/quiz/200-fragor",
  },
  {
    title: "Jag har aldrig",
    emoji: "🙅‍♂️",
    slug: "jag-har-aldrig",
    color: "bg-yellow-50",
    category: "dricklekar-och-drickspel",
    url: "/dricklekar-och-drickspel/jag-har-aldrig",
  },
  {
    title: "Pekleken",
    emoji: "👉",
    slug: "pekleken",
    color: "bg-purple-50",
    category: "dricklekar-och-drickspel",
    url: "/dricklekar-och-drickspel/pekleken",
  },
  {
    title: "Snurra flaskan",
    emoji: "🍾",
    slug: "snurra-flaskan",
    color: "bg-green-50",
    category: "dricklekar-och-drickspel",
    url: "/dricklekar-och-drickspel/snurra-flaskan",
  },
  {
    title: "Sanning eller Konka",
    emoji: "🎭",
    slug: "sanning-eller-konka",
    color: "bg-blue-50",
    category: "sallskapsspel",
    url: "/sallskapsspel/sanning-eller-konka",
  },
  {
    title: "Vem i rummet",
    emoji: "👥",
    slug: "vem-i-rummet",
    color: "bg-purple-50",
    category: "dricklekar-och-drickspel",
    url: "/dricklekar-och-drickspel/vem-i-rummet",
  },
  {
    title: "Gissa låten",
    emoji: "🎵",
    slug: "gissa-laten",
    color: "bg-blue-50",
    category: "quiz",
    url: "/quiz/gissa-laten",
  },
  {
    title: "Charades",
    emoji: "🎬",
    slug: "charades",
    color: "bg-amber-50",
    category: "sallskapsspel",
    url: "/sallskapsspel/charades",
  },
  {
    title: "0-100 Frågor",
    emoji: "🧠",
    slug: "0-100-fragor",
    color: "bg-purple-50",
    category: "quiz",
    url: "/quiz/0-100-fragor",
  },
  {
    title: "Utmaningar",
    emoji: "🔥",
    slug: "utmaningar",
    color: "bg-red-50",
    category: "sallskapsspel",
    url: "/sallskapsspel/utmaningar",
  },
  {
    title: "Rygg mot rygg",
    emoji: "🪑",
    slug: "rygg-mot-rygg",
    color: "bg-orange-50",
    category: "dricklekar-och-drickspel",
    url: "/dricklekar-och-drickspel/rygg-mot-rygg",
  },
] as const;

export const HERO_CARDS = [
  {
    title: "Med andra ord",
    emoji: "🎯",
    slug: "med-andra-ord",
    color: "bg-gray-50",
    url: "/sallskapsspel/med-andra-ord",
  },
  {
    title: "200 Frågor",
    emoji: "❓",
    slug: "200-fragor",
    color: "bg-blue-50",
    url: "/quiz/200-fragor",
  },
  {
    title: "Jag har aldrig",
    emoji: "🙅‍♂️",
    slug: "jag-har-aldrig",
    color: "bg-yellow-50",
    url: "/dricklekar-och-drickspel/jag-har-aldrig",
  },
];

export const ANIMATION_POSITIONS = [
  // Position 1
  [
    {
      top: 20,
      right: 20,
      rotate: 6,
      scale: 1,
      zIndex: 30,
      opacity: 1,
      blur: 0,
    },
    {
      top: 100,
      right: 60,
      rotate: -8,
      scale: 0.95,
      zIndex: 20,
      opacity: 0.9,
      blur: 1,
    },
    {
      top: 180,
      right: 30,
      rotate: 12,
      scale: 0.9,
      zIndex: 10,
      opacity: 0.8,
      blur: 2,
    },
  ],
  // Position 2
  [
    {
      top: 180,
      right: 30,
      rotate: 12,
      scale: 0.9,
      zIndex: 10,
      opacity: 0.8,
      blur: 2,
    },
    {
      top: 20,
      right: 20,
      rotate: 6,
      scale: 1,
      zIndex: 30,
      opacity: 1,
      blur: 0,
    },
    {
      top: 100,
      right: 60,
      rotate: -8,
      scale: 0.95,
      zIndex: 20,
      opacity: 0.9,
      blur: 1,
    },
  ],
  // Position 3
  [
    {
      top: 100,
      right: 60,
      rotate: -8,
      scale: 0.95,
      zIndex: 20,
      opacity: 0.9,
      blur: 1,
    },
    {
      top: 180,
      right: 30,
      rotate: 12,
      scale: 0.9,
      zIndex: 10,
      opacity: 0.8,
      blur: 2,
    },
    {
      top: 20,
      right: 20,
      rotate: 6,
      scale: 1,
      zIndex: 30,
      opacity: 1,
      blur: 0,
    },
  ],
];

export const QUESTIONS_DATA = {
  popular: [
    "Vad är din största osäkerhet?",
    "Vad är din bästa egenskap?",
    "Om du kunde resa vart som helst, vart skulle du åka?",
    "Vad är din största rädsla?",
    "Vad är ditt bästa minne?",
  ],
  party: [
    "Vem i rummet skulle du vilja byta liv med för en dag?",
    "Berätta om ditt mest pinsamma ögonblick",
    "Vem i rummet skulle klara sig bäst i en zombieapokalyps?",
    "Vem i rummet skulle du ringa om du hamnade i fängelse?",
    "Vem i rummet skulle du vilja vara fast i en hiss med?",
  ],
  fun: [
    "Vilken superkraft skulle du vilja ha?",
    "Om du var ett djur, vilket skulle du vara?",
    "Vilken är din favoritfilm?",
    "Vad skulle du göra om du vann en miljon kronor?",
    "Vilken är din favoritmat?",
  ],
  extreme: [
    "Vad är det galnaste du någonsin gjort?",
    "Berätta om ditt värsta dejt",
    "Vad är din största hemlighet?",
    "Vad är det mest olagliga du gjort?",
    "Vad är det mest extrema du skulle göra för pengar?",
  ],
};
